### PR TITLE
Add CloudApp upload support

### PR DESCRIPTION
**Pull request by goncalossilva**
This PR adds CloudApp support, similar to the existing Imgur support.

Docs: https://github.com/cloudapp/api

It's not perfect, and I believe some improvements could be made, namely:
* UI-wise, using a new tab for every integration does not scale. I've considered adding an "Integrations" tab and moving both Imgur and CloudApp under there, making them configurable one at a time via a master dropdown.
* Code-wise, there is a lot of repetition between Imgur and CloudApp. It affects not only their respective code, but also setup and usage within `extension.js`, `indicator.js`, `notifications.js`, `prefs.js`, etc. Conceptually, this is not actual repetition, as nothing guarantees that integrations behave similarly to Imgur, although CloudApp does. Regardless, there's a high likelihood that this could be much improved by using different abstractions within the code.
* Test-wise, there is no test such as [Imgur's](https://github.com/OttoAllmendinger/gnome-shell-screenshot/blob/master/tests/uploadImgurTest.js). The main reason being that CloudApp requires authentication, and I honestly have no clue about the best way to pass these (environment variables?).

I have been maintaining this fork on the side for over a year now, with the goal of getting to those above at some point, but the truth is that I don't foresee short-term availability to work on any of these. Considering they are improvements (the extension works nicely as it is), I think it's more beneficial to submit this and let you be the judge than keep postponing it indefinitely.

Cheers, and thanks for an awesome extension!

### CODE REVIEW

**Comment by OttoAllmendinger** [comment]
Sorry, I just noticed this PR now. It looks good, but I think I will reorganize it a bit before merging.

**Comment by goncalossilva** [comment]
That is fine, feel free to reorganize things in any way you think is better! Let me know if I can help.

**Comment by goncalossilva** [comment]
Updated the PR to adhere to the recent ES6 changes.

**Comment by goncalossilva** [comment]
Updated with the latest updates to the CloudApp API.

**Comment by chrisma** [comment]
FYI: `The API is no longer supported`
https://github.com/cloudapp/api
image

**Comment by goncalossilva** [comment]
Thanks @chrisma. The public API [still works fine](https://cl.ly/d52fb1b1831e/gnome-shell-screenshot-SPKVK0.png), but it's unclear for how long and this PR no longer makes sense. Closing it. :+1:

**Pull request closed without merging**
