### PR TITLE
Unsafe mode fix: xdg-desktop-portal 

### PR DESCRIPTION
**Pull request by mc-cat-tty**
Due to Gnome41's developers safety choices, gnome-shell proxies's callers need to be whitelisted (hardcoded array). This workaround employs a different screenshot proxy (exposed by xdg-desktop-portal).

Changes:
- disabled dbus unsafe mode
- screenshot proxy migration: from gnome-shell-screenshot to xdg-desktop-portal screenshot proxy
- new dependencies: xdg-desktop-portal-gtk, xdg-desktop-portal-gnome

Known issues:
- doesn't work in main Gnome session, but only in nested one (I need some help :) )
- users have to interact with xdg portal's modal window to share the screenshot
- select window and select area no longer work from the extension

### CODE REVIEW

**Comment by OttoAllmendinger** [comment]
Thank you, this is useful for me.

I was already working on a change using the new desktop portal and you are providing some missing pieces.

However I will have to do a larger change and remove the desktop/window/area options since they are now pointless (decided by the portal).

**Comment by mc-cat-tty** [comment]
Yes, I know, the portal provides a single modal for all the three options; I'm very disappointed because this way the usability of the extension decreases.

I've read around the web that xdg-portal maintainers will probably remove the need for human interaction after the first time.

I had some issues receiving "Response" signal inside auxhelper.js (even by setting every parameter of _subscribe_ function to null), therefore I tried to move the event listener inside extension.js and it worked (I don't know why, I think signal destination didn't match in the first way). Working with dbus and xdg-portal is very complex because of the lacking of documentation...

P.S.: sorry for my messy code

**Comment by OttoAllmendinger** [comment]
please try https://github.com/OttoAllmendinger/gnome-shell-screenshot/tree/gnome41-portal-screenshot

**Comment by mc-cat-tty** [comment]
It works! Thx

**Pull request closed without merging**
