### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by pkomur**

### CODE REVIEW

**Comment by OttoAllmendinger** [comment]
Thanks for your work! I added a few strings, could you maybe update it?

**Comment by pkomur** [comment]
OK, I'll check it.

Piotr Komur
(pkomur@gmail.com)

9 sty 2017 1:51 PM "Otto Allmendinger" <notifications@github.com>
napisał(a):

**Comment by pkomur** [comment]
Please add new strings to _gnome-shell-screenshot.pot_ file.

**Comment by OttoAllmendinger** [comment]
pot file is updated on master: https://github.com/OttoAllmendinger/gnome-shell-screenshot/commit/b3fe5889d3dd6edbb07712e495e1f85e1a3028c4

**Comment by pkomur** [comment]
OK, but please add also "_Parameters_" string to pot file.

**Comment by RaphaelRochet** [comment]
Let me do it, along with french translation again.

**Comment by RaphaelRochet** [comment]
(Done with #18 )

**Comment by OttoAllmendinger** [comment]
Thanks for your work, I merged it in here: https://github.com/OttoAllmendinger/gnome-shell-screenshot/commit/618d01d47cea4946134cae3506161232588e0f02

Could you help out with this translation? https://github.com/OttoAllmendinger/gnome-shell-screenshot/blob/22cd4aab53ac665277922d06e231a52bdc56cc0c/src/locale/pl/pl.po#L122-L125

**Pull request closed without merging**
